wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716034537
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 23
      - 37
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
datamodule.batch_size:
  desc: null
  value: 55
epochs:
  desc: null
  value: 45
optim.lr:
  desc: null
  value: 0.0014968828307668014
