_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomResizedCrop
    size: [224, 224]
  - _target_: torchvision.transforms.RandomRotation
    degrees: 30
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.2
  - _target_: torchvision.transforms.RandomAffine
    degrees: 0
    translate: [0.1, 0.1]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
