batch_size: 1
data_dir: ${root_dir}/dataset
defaults:
- image_generator: fromage_particulier
- dataset_generator: prompt
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
labels_file: '${root_dir}/list_of_single_cheese/patato.txt '
root_dir: ${hydra:runtime.cwd}
