_target_: data.dataset_generators.advanced.AdvancedPromptsDatasetGenerator
generator: ${image_generator}
batch_size: ${batch_size}
<<<<<<< HEAD
output_dir: ${data_dir}/train/advanced_prompt_advanced_models
num_images_per_label: 1
=======
output_dir: ${data_dir}/train/advanced_prompt_advanced_models/00-v2
num_images_per_label: 40
>>>>>>> a90b4086 (final version)
